name: telegram-roles-bot
version: 0.1.0.0
github: "Github username here/telegram-roles-bot"
license: MIT
author: "Hubert Badocha"
maintainer: "Author email here"
copyright: "2019 Author name here"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Bring roles to your telegram group chat
category: Web

description: Please see the README on GitHub at https://github.com/badochov/telegram-bot-simple.git#readme

dependencies:
  - base >= 4.7 && < 5
  - text == 1.2.5.0
  - unordered-containers == 0.2.17.0
  - containers == 0.6.4.1
  - mtl == 2.2.2
  - hashable == 1.3.5.0
  - cereal == 0.5.8.2
  - directory == 1.3.6.2
  - atomic-write == 0.2.0.7
  - bytestring == 0.10.12.1
  - filepath == 1.4.2.1
  - telegram-bot-simple
  - warp
  - warp-tls

library:
  source-dirs: src

executables:
  telegram-roles-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - telegram-roles-bot

tests:
  telegram-roles-bot-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - telegram-roles-bot
