name: telegram-roles-bot
version: 0.2.0.0
github: "badochov/telegram-roles-bot"
license: MIT
author: "Hubert Badocha"
maintainer: "badocha.hubert@gmail.com"
copyright: "2023 Hubert Badocha"

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Bring roles to your telegram group chat
category: Web

description: Please see the README on GitHub at https://github.com/badochov/telegram-roles-bot.git#README.md

dependencies:
  - base >= 4.9 && < 5
  - text
  - unordered-containers
  - containers
  - mtl
  - hashable
  - cereal
  - directory
  - atomic-write
  - bytestring
  - filepath
  - telegram-bot-simple == 0.6.1

library:
  source-dirs: src

executables:
  telegram-roles-bot-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - telegram-roles-bot
